apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: grafana-oauth
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLIENT_ID
      remoteRef:
        key: 03cc81ed-3e3a-4c3a-8299-b45100f75291
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: 0b9002e5-42be-4403-88d9-b45100f752cf
