apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bikepal-data-protection
  namespace: bikepal
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-critical
