apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bikepal-secrets
  namespace: bikepal
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager-bikepal
  target:
    name: bikepal-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: Database__ConnectionString
      remoteRef:
        key: 4ff39308-1a41-4521-977e-b43a0121c940
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: Strava__ClientId
      remoteRef:
        key: 120eeac9-8b13-4161-8fc0-b43a01210b7d
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: Strava__ClientSecret
      remoteRef:
        key: 88194c47-a3c7-46c6-8d92-b43a0121203b
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
