apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bikepal-secrets
  namespace: bikepal
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager-bikepal
  target:
    name: bikepal-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: Database__ConnectionString
      remoteRef:
        key: 00000000-0000-0000-0000-000000000001
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: Strava__ClientId
      remoteRef:
        key: 00000000-0000-0000-0000-000000000002
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: Strava__ClientSecret
      remoteRef:
        key: 00000000-0000-0000-0000-000000000003
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
