apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bikepal-ghcr
  namespace: bikepal
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager-bikepal
  target:
    name: bikepal-ghcr
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "carnufex",
                "password": "{{ .GHCR_PAT }}",
                "auth": "{{ printf "carnufex:%s" .GHCR_PAT | b64enc }}"
              }
            }
          }
  data:
    - secretKey: GHCR_PAT
      remoteRef:
        key: 00000000-0000-0000-0000-000000000004
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
