apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: User applications
  sourceRepos:
  - https://github.com/carnufex/Rosenvalls-Homelab.git
  - https://github.com/infiniflow/ragflow.git
  destinations:
  - namespace: rosenvall-devops
    server: https://kubernetes.default.svc
  - namespace: bikepal
    server: https://kubernetes.default.svc
  - namespace: homeassistant
    server: https://kubernetes.default.svc
  - namespace: hub-central
    server: https://kubernetes.default.svc
  - namespace: headlamp
    server: https://kubernetes.default.svc
  - namespace: matplan
    server: https://kubernetes.default.svc
  - namespace: media
    server: https://kubernetes.default.svc
  - namespace: ollama
    server: https://kubernetes.default.svc
  - namespace: ragflow
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: ""
    kind: PersistentVolume
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceBlacklist:
  - group: argoproj.io
    kind: AppProject
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: ApplicationSet
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
