apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: User applications
  sourceRepos:
  - https://github.com/carnufex/Rosenvalls-Homelab.git
  - https://github.com/infiniflow/ragflow.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: PersistentVolume
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
