apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: 6f4ce89e-4452-4733-9153-b3c4007e3d75
    - secretKey: dex.authentik.clientId
      remoteRef:
        key: 18cfb7f0-977a-4e6c-a27e-b3c4007f398e
