server:
  extraArgs:
    - --insecure
  ingress:
    enabled: false

configs:
  cm:
    create: true
    admin.enabled: "false"
    url: https://argo.rosenvall.se
    kustomize.buildOptions: --enable-helm
    dex.config: |
      connectors:
      - config:
          issuer: https://authentik.rosenvall.se/application/o/argocd/
          clientID: $dex.authentik.clientId
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
  params:
    server.insecure: true
  rbac:
    create: true
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly
