apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/name: immich-postgresql
    app.kubernetes.io/component: database
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-critical
  resources:
    requests:
      storage: 10Gi
