apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-database-password
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-database
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-14"
spec:
  refreshPolicy: CreatedOnce
  target:
    name: immich-database
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: immich-database-password
