apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
spec:
  capacity:
    storage: 7Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - hard
    - nointr
  nfs:
    server: 192.168.1.230
    path: /srv/nfs/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 7Ti
