apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/carnufex/Rosenvalls-Homelab.git
      revision: HEAD
      directories:
      - path: kubernetes/infrastructure/*/*
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if eq .path.basename "gateway-api" }}0{{ else if eq .path.basename "cilium" }}1{{ else if eq .path.basename "longhorn" }}2{{ else if eq .path.basename "cloudnative-pg" }}3{{ else if eq .path.basename "cert-manager" }}4{{ else if eq .path.basename "external-secrets" }}5{{ else if eq .path.basename "gateway" }}6{{ else if eq .path.basename "cloudflared" }}7{{ else if eq .path.basename "argocd" }}8{{ else if eq .path.basename "authentik-db-prereqs" }}9{{ else if eq .path.basename "authentik-runtime" }}10{{ else if eq .path.basename "authentik-db-ops" }}11{{ else if or (eq .path.basename "loki-stack") (eq .path.basename "prometheus-stack") }}11{{ else }}12{{ end }}'
        argocd.argoproj.io/depends-on: '{{ if eq .path.basename "external-secrets" }}argocd/cert-manager{{ else if eq .path.basename "cloudnative-pg" }}argocd/longhorn{{ else if eq .path.basename "gateway" }}argocd/cert-manager{{ else if eq .path.basename "cloudflared" }}argocd/external-secrets,argocd/gateway{{ else if eq .path.basename "argocd" }}argocd/external-secrets,argocd/gateway{{ else if eq .path.basename "authentik-db-prereqs" }}argocd/cloudnative-pg,argocd/external-secrets{{ else if eq .path.basename "authentik-runtime" }}argocd/authentik-db-prereqs,argocd/gateway{{ else if eq .path.basename "authentik-db-ops" }}argocd/authentik-db-prereqs{{ else if or (eq .path.basename "loki-stack") (eq .path.basename "prometheus-stack") }}argocd/longhorn,argocd/gateway{{ else }}{{ end }}'
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/carnufex/Rosenvalls-Homelab.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: "10s"
            factor: 2
            maxDuration: "3m"
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.volumeClaimTemplates[].apiVersion
            - .spec.volumeClaimTemplates[].kind
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[].remoteRef.conversionStrategy
            - .spec.data[].remoteRef.decodingStrategy
            - .spec.data[].remoteRef.metadataPolicy
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
        - group: gateway.networking.k8s.io
          kind: Gateway
          jsonPointers:
            - /status
          jqPathExpressions:
            - .spec.listeners[].tls.certificateRefs[].group
            - .spec.listeners[].tls.certificateRefs[].kind
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          jsonPointers:
            - /status
          jqPathExpressions:
            - .spec.parentRefs[].group
            - .spec.parentRefs[].kind
            - .spec.rules[].backendRefs[].group
            - .spec.rules[].backendRefs[].kind
            - .spec.rules[].backendRefs[].weight
        - group: postgresql.cnpg.io
          kind: Cluster
          jsonPointers:
            - /status
          jqPathExpressions:
            - .spec.monitoring
            - .spec.bootstrap.initdb.encoding
            - .spec.bootstrap.initdb.localeCType
            - .spec.bootstrap.initdb.localeCollate
            - .spec.postgresGID
            - .spec.postgresUID
