apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/carnufex/Rosenvalls-Homelab.git
    targetRevision: HEAD
    path: kubernetes/infrastructure/network/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "3m"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /status
      jqPathExpressions:
        - .spec.listeners[].tls.certificateRefs[].group
        - .spec.listeners[].tls.certificateRefs[].kind
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /status
      jqPathExpressions:
        - .spec.parentRefs[].group
        - .spec.parentRefs[].kind
        - .spec.rules[].backendRefs[].group
        - .spec.rules[].backendRefs[].kind
        - .spec.rules[].backendRefs[].weight
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status
      jqPathExpressions:
        - .spec.monitoring
        - .spec.bootstrap.initdb.encoding
        - .spec.bootstrap.initdb.localeCType
        - .spec.bootstrap.initdb.localeCollate
        - .spec.postgresGID
        - .spec.postgresUID
