apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rules.yaml
  - vendor/plugin-barman-cloud-v0.5.0/manifest.yaml

helmCharts:
  - name: cloudnative-pg
    valuesFile: helm-values.yaml
    releaseName: cloudnative-pg
    namespace: cnpg-system
    version: 0.27.0
    includeCRDs: true
    repo: https://cloudnative-pg.github.io/charts
    kubeVersion: v1.31.1

patches:
  - path: deployment-hardening-patch.yaml
