apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-blueprint-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ARGOCD_CLIENT_ID: "{{ .ARGOCD_CLIENT_ID }}"
        ARGOCD_CLIENT_SECRET: "{{ .ARGOCD_CLIENT_SECRET }}"
  data:
    - secretKey: ARGOCD_CLIENT_ID
      remoteRef:
        key: 18cfb7f0-977a-4e6c-a27e-b3c4007f398e
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: 6f4ce89e-4452-4733-9153-b3c4007e3d75
