apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: s3-backup-credentials # Name in Bitwarden
        property: S3_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: s3-backup-credentials
        property: S3_SECRET_ACCESS_KEY
    - secretKey: ENDPOINT
      remoteRef:
        key: s3-backup-credentials
        property: S3_ENDPOINT
