apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: a7be37ca-2b82-4050-b42b-b3eb0179367c
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: c38a2bfc-629f-40fe-8fe4-b3eb01794aad
    - secretKey: ENDPOINT
      remoteRef:
        key: f1ad7686-5ca5-4315-8df0-b3eb01796694
