apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ngm-onedrive-backup
  namespace: ngm
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ngm-onedrive-backup
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        rclone.conf: "{{ .RCLONE_CONFIG }}"
  data:
    - secretKey: RCLONE_CONFIG
      remoteRef:
        key: HOMEASSISTANT_RCLONE_CONFIG
        conversionStrategy: Default
        decodingStrategy: Base64
        metadataPolicy: None
