apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager-bikepal
spec:
  conditions:
    - namespaces:
        - bikepal
  provider:
    bitwardensecretsmanager:
      organizationID: "6ce343f0-efbd-453f-836a-b39f0088b290"
      projectID: "9ba2b38c-218c-4ae6-ae99-b43a0120e6c1"
      apiURL: "https://api.bitwarden.eu"
      identityURL: "https://identity.bitwarden.eu"
      bitwardenServerSDKURL: "https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998"
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
        namespace: external-secrets
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
