apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-sdk-server
  namespace: external-secrets
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-cert-controller
  namespace: external-secrets
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  revisionHistoryLimit: 3
