apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

resources:
  - namespace.yaml
  - cluster-secret-store.yaml
  - cluster-secret-store-matplan.yaml
  - cluster-secret-store-rosenvall-devops.yaml
  - certs.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.10.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml
    kubeVersion: v1.37.0

patches:
  - path: deployment-hardening-patch.yaml
