apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - namespace.yaml
  - http-route.yaml
  - backup-target-disabled.yaml
  - recurring-jobs.yaml
  - storage-class-critical.yaml
  - storage-class-observability.yaml
  - storage-class-observability-single.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.10.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
    includeCRDs: true
    kubeVersion: v1.31.1

patches:
  - path: deployment-hardening-patch.yaml
