apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-hourly-snapshot
  namespace: longhorn-system
spec:
  name: default-hourly-snapshot
  task: snapshot
  cron: "0 * * * *"
  retain: 24
  concurrency: 2
  groups:
    - default
  labels:
    backup-tier: default
    cadence: hourly
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: r2-small-config-daily-backup
  namespace: longhorn-system
spec:
  name: r2-small-config-daily-backup
  task: backup
  cron: "30 3 * * *"
  retain: 3
  concurrency: 2
  groups:
    - r2-small-config
  labels:
    backup-tier: r2-free
    cadence: daily
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: r2-plex-config-weekly-backup
  namespace: longhorn-system
spec:
  name: r2-plex-config-weekly-backup
  task: backup
  cron: "45 4 * * 0"
  retain: 1
  concurrency: 1
  groups:
    - r2-plex-config
  labels:
    backup-tier: r2-free
    cadence: weekly
