apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatebound-mariadb-data
  namespace: gatebound
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
