apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-blueprint-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ARGOCD_CLIENT_ID: "{{ .ARGOCD_CLIENT_ID }}"
        ARGOCD_CLIENT_SECRET: "{{ .ARGOCD_CLIENT_SECRET }}"
        GRAFANA_CLIENT_ID: "{{ .GRAFANA_CLIENT_ID }}"
        GRAFANA_CLIENT_SECRET: "{{ .GRAFANA_CLIENT_SECRET }}"
        HEADLAMP_CLIENT_ID: "{{ .HEADLAMP_CLIENT_ID }}"
        HEADLAMP_CLIENT_SECRET: "{{ .HEADLAMP_CLIENT_SECRET }}"
        RAGFLOW_CLIENT_ID: "{{ .RAGFLOW_CLIENT_ID }}"
        RAGFLOW_CLIENT_SECRET: "{{ .RAGFLOW_CLIENT_SECRET }}"
        SEERR_CLIENT_ID: "{{ .SEERR_CLIENT_ID }}"
        SEERR_CLIENT_SECRET: "{{ .SEERR_CLIENT_SECRET }}"
  data:
    - secretKey: ARGOCD_CLIENT_ID
      remoteRef:
        key: 18cfb7f0-977a-4e6c-a27e-b3c4007f398e
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: 6f4ce89e-4452-4733-9153-b3c4007e3d75
    - secretKey: GRAFANA_CLIENT_ID
      remoteRef:
        key: 03cc81ed-3e3a-4c3a-8299-b45100f75291
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: 0b9002e5-42be-4403-88d9-b45100f752cf
    - secretKey: HEADLAMP_CLIENT_ID
      remoteRef:
        key: ce3ea8bf-9224-469b-9602-b45100f752ff
    - secretKey: HEADLAMP_CLIENT_SECRET
      remoteRef:
        key: 3ab7688e-ffc2-4c41-8179-b45100f75332
    - secretKey: RAGFLOW_CLIENT_ID
      remoteRef:
        key: b3c6ade4-091d-47f6-be7f-b45100f75369
    - secretKey: RAGFLOW_CLIENT_SECRET
      remoteRef:
        key: b01491b8-86ac-4a5c-9f7c-b45100f768e9
    - secretKey: SEERR_CLIENT_ID
      remoteRef:
        key: f38e7dd9-b37e-45ba-8b56-b452006fb458
    - secretKey: SEERR_CLIENT_SECRET
      remoteRef:
        key: 44d5d0e9-62f1-4335-899f-b452006fb48c
