apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matplan-secrets
  namespace: matplan
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager-matplan
  target:
    name: matplan-secrets
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__MatPlan
      remoteRef:
        key: 07a35bfb-a56d-4754-b7bb-b4180140bd3c
    - secretKey: Jwt__SigningKey
      remoteRef:
        key: c68e34cb-bff0-45be-a17f-b4180140f34e
    - secretKey: GoogleAuth__ClientSecret
      remoteRef:
        key: f51b5b77-0b40-4fc5-aeee-b41801429ca1
