apiVersion: apps/v1
kind: Deployment
metadata:
  name: matplan-frontend
  namespace: matplan
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matplan-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matplan-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/carnufex/matplan-frontend@sha256:238486d34252f35dc8a64fde840a443ccbb626076826a5868c675a194ea4dd22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
