apiVersion: v1
kind: Service
metadata:
  name: matplan-frontend
  namespace: matplan
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: matplan-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
