apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - configmap.yaml
  - externalsecret.yaml
  - data-protection-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - httproute.yaml
