apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matplan-piper-data
  namespace: matplan
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn-critical
