<#
.SYNOPSIS
  Regenerates tofu/talos/inline-manifests/cilium-install.yaml - the Cilium that Talos
  applies at bootstrap, before ArgoCD exists - from the SAME chart version and values as
  the GitOps app (kubernetes/infrastructure/network/cilium), so a cold rebuild comes up on
  the CNI version the cluster actually runs.

.DESCRIPTION
  helm template with the GitOps values.yaml, but with Hubble (+relay, +UI) disabled:
  with Hubble on, helm embeds a freshly generated CA and Hubble key pairs in the output, and
  this repo is public. The bootstrap CNI only has to carry the cluster until ArgoCD syncs
  the real Cilium app, which turns Hubble on and generates its certificates in-cluster.

  Run it whenever the Cilium chart version or values.yaml change (update-center flags the
  bootstrap manifest when it lags behind the GitOps chart).

.EXAMPLE
  .\scripts\render-cilium-bootstrap.ps1
#>
[CmdletBinding()]
param(
  [string]$Version,      # default: the version pinned in the GitOps kustomization
  [string]$KubeVersion   # default: kubeVersion from the same kustomization
)
$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$kustomization = Get-Content -Raw (Join-Path $Root 'kubernetes\infrastructure\network\cilium\kustomization.yaml')
if (-not $Version)     { $Version     = [regex]::Match($kustomization, '(?m)^\s*version:\s*([0-9][^\s#]*)').Groups[1].Value }
if (-not $KubeVersion) { $KubeVersion = [regex]::Match($kustomization, '(?m)^\s*kubeVersion:\s*(\S+)').Groups[1].Value }
if (-not $Version) { throw 'could not read the Cilium chart version from the GitOps kustomization' }
$values = Join-Path $Root 'kubernetes\infrastructure\network\cilium\values.yaml'
$out    = Join-Path $Root 'tofu\talos\inline-manifests\cilium-install.yaml'

# Isolated helm cache: a stale local repo index must not break (or influence) the render.
$cache = Join-Path $env:TEMP ('helm-cilium-' + [guid]::NewGuid().ToString('n'))
New-Item -ItemType Directory -Path $cache | Out-Null
$env:HELM_REPOSITORY_CACHE  = $cache
$env:HELM_REPOSITORY_CONFIG = Join-Path $cache 'repositories.yaml'
try {
  $helmArgs = @('template', 'cilium', 'cilium', '--repo', 'https://helm.cilium.io/', '--version', $Version,
    '-n', 'kube-system', '-f', $values,
    '--set', 'hubble.enabled=false', '--set', 'hubble.relay.enabled=false', '--set', 'hubble.ui.enabled=false')
  if ($KubeVersion) { $helmArgs += @('--kube-version', $KubeVersion) }
  $rendered = & helm @helmArgs
  if ($LASTEXITCODE) { throw 'helm template failed' }
  $text = ($rendered -join "`n") + "`n"
  if ($text -match 'PRIVATE KEY|LS0tLS1CRUdJTi') { throw 'render contains key material - refusing to write it into a public repo' }
  $header = "# GENERATED by scripts/render-cilium-bootstrap.ps1 - do not edit.`n# Cilium $Version (kube $KubeVersion), GitOps values with Hubble disabled (no key material in Git).`n"
  [IO.File]::WriteAllText($out, $header + $text, (New-Object Text.UTF8Encoding($false)))
  Write-Host "wrote $out  (Cilium $Version)"
} finally {
  Remove-Item -Recurse -Force $cache -ErrorAction SilentlyContinue
}
