apiVersion: v1
kind: Service
metadata:
  name: rosenvall-devops-forgejo
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/name: rosenvall-devops-forgejo
    app.kubernetes.io/part-of: rosenvall-devops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rosenvall-devops-forgejo
  ports:
    - name: http
      port: 3000
      targetPort: http
