apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rosenvall-devops-forgejo-data
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
