apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: rosenvall-devops-forgejo-admin-password
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rosenvall-devops-forgejo-admin
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 87600h
  target:
    name: rosenvall-devops-forgejo-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        username: rdo
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: rosenvall-devops-forgejo-admin-password
