apiVersion: v1
kind: Service
metadata:
  name: rosenvall-devops-frontend
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: rosenvall-devops-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
