apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rosenvall-devops-github-app
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager-rosenvall-devops
  target:
    name: rosenvall-devops-github-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        app-id: "{{ .GITHUB_APP_ID }}"
        app-slug: "{{ .GITHUB_APP_SLUG }}"
        private-key: "{{ .GITHUB_APP_PRIVATE_KEY }}"
  data:
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: 889236e6-b066-4834-8e34-b452006fb3f5
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GITHUB_APP_SLUG
      remoteRef:
        key: 6851310c-d451-4fda-88b2-b452006fb41d
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: 11702f2f-0607-4104-8f5e-b452006fd9e2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
