apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - configmap.yaml
  - state-pvc.yaml
  - codex-home-pvc.yaml
  - ghcr-image-pull-secret.yaml
  - serviceaccount.yaml
  - preview-rbac.yaml
  - preview-cleaner-rbac.yaml
  - preview-cleaner-configmap.yaml
  - preview-cleaner-cronjob.yaml
  - api-service.yaml
  - frontend-service.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - httproute.yaml
