apiVersion: v1
kind: ServiceAccount
metadata:
  name: rosenvall-devops-api
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
imagePullSecrets:
  - name: rosenvall-devops-ghcr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rosenvall-devops-runtime
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
imagePullSecrets:
  - name: rosenvall-devops-ghcr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rosenvall-devops-frontend
  namespace: rosenvall-devops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
imagePullSecrets:
  - name: rosenvall-devops-ghcr
