# The tunnel token is decoded into this credentials file by the initContainer.
tunnel: 8cde49fc-7eed-4521-b673-d406599e5b6e
credentials-file: /etc/cloudflared/creds/tunnel.json

metrics: 0.0.0.0:2000

ingress:
  # Route all traffic for *.rosenvall.se to the Cilium External Gateway.
  - hostname: "*.rosenvall.se"
    service: https://cilium-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      matchSNItoHost: true
      noTLSVerify: true

  # Route root domain.
  - hostname: rosenvall.se
    service: https://cilium-gateway-external.gateway.svc.cluster.local:443
    originRequest:
      originServerName: rosenvall.se
      noTLSVerify: true

  # Catch-all.
  - service: http_status:404
