apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-critical
