apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-wireguard-config
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: deluge-wireguard-config
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: wg0.conf
      remoteRef:
        key: e5889786-d712-49f1-be3b-b4280070b18b
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
