apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deluge-vpn-leak-check-slack
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: deluge-vpn-leak-check-slack
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: abeef982-e4eb-4968-9d95-b472015a50c1
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
