apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media
spec:
  selector:
    app.kubernetes.io/name: jackett
  ports:
    - name: http
      port: 9117
      targetPort: http
      protocol: TCP
