apiVersion: v1
kind: ConfigMap
metadata:
  name: media-runtime
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  TZ: Europe/Stockholm
  PUID: "1000"
  PGID: "1000"
  UMASK_SET: "000"
  DELUGE_LOGLEVEL: error
