apiVersion: v1
kind: Service
metadata:
  name: plex-oauth2-proxy
  namespace: media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: plex-oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: http
