apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-oauth2-proxy
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: plex-oauth2-proxy
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        client-id: "{{ .PLEX_CLIENT_ID }}"
        client-secret: "{{ .PLEX_CLIENT_SECRET }}"
        cookie-secret: "{{ .PLEX_OAUTH2_COOKIE_SECRET }}"
  data:
    - secretKey: PLEX_CLIENT_ID
      remoteRef:
        key: 800af3b9-2af7-469f-9290-b45200e04479
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: PLEX_CLIENT_SECRET
      remoteRef:
        key: 71c51989-51f3-4a92-b1ed-b45200e044a6
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: PLEX_OAUTH2_COOKIE_SECRET
      remoteRef:
        key: b5f316fe-589c-4b5a-91d6-b45200e04596
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
