apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  selector:
    app.kubernetes.io/name: plex
  ports:
    - name: web
      port: 32400
      targetPort: web
      protocol: TCP
