apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-oauth2-proxy
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: seerr-oauth2-proxy
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        client-id: "{{ .SEERR_CLIENT_ID }}"
        client-secret: "{{ .SEERR_CLIENT_SECRET }}"
        cookie-secret: "{{ .SEERR_OAUTH2_COOKIE_SECRET }}"
  data:
    - secretKey: SEERR_CLIENT_ID
      remoteRef:
        key: f38e7dd9-b37e-45ba-8b56-b452006fb458
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SEERR_CLIENT_SECRET
      remoteRef:
        key: 44d5d0e9-62f1-4335-899f-b452006fb48c
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SEERR_OAUTH2_COOKIE_SECRET
      remoteRef:
        key: 8a1162ee-049a-4130-9a4a-b452006fb4ba
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
