apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect-internal
  namespace: gateway
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: http
  hostnames:
    - authentik.rosenvall.local
    - deluge.rosenvall.local
    - grafana.rosenvall.local
    - homeassistant.rosenvall.local
    - hub-central.rosenvall.local
    - jackett.rosenvall.local
    - longhorn.rosenvall.local
    - overseerr.rosenvall.local
    - plex.rosenvall.local
    - prometheus.rosenvall.local
    - radarr.rosenvall.local
    - ragflow.rosenvall.local
    - sonarr.rosenvall.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
